/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AgenceProspect API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface SuccessResponse {
  success: boolean;
  message?: string;
}

export type LeadStatus = typeof LeadStatus[keyof typeof LeadStatus];


export const LeadStatus = {
  new: 'new',
  contacted: 'contacted',
  scheduled: 'scheduled',
  rejected: 'rejected',
} as const;

export interface Lead {
  id: string;
  phone: string;
  title: string;
  price?: string;
  surface?: string;
  rooms?: string;
  city: string;
  description?: string;
  url?: string;
  status: LeadStatus;
  confidenceScore?: number;
  isAgency?: boolean;
  generatedMessage?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface LeadsResponse {
  leads: Lead[];
  total: number;
}

export interface CreateLeadRequest {
  phone: string;
  title: string;
  price?: string;
  surface?: string;
  rooms?: string;
  city: string;
  description?: string;
  url?: string;
  isAgency?: boolean;
}

export type UpdateLeadRequestStatus = typeof UpdateLeadRequestStatus[keyof typeof UpdateLeadRequestStatus];


export const UpdateLeadRequestStatus = {
  new: 'new',
  contacted: 'contacted',
  scheduled: 'scheduled',
  rejected: 'rejected',
} as const;

export interface UpdateLeadRequest {
  status?: UpdateLeadRequestStatus;
  generatedMessage?: string;
  confidenceScore?: number;
  isAgency?: boolean;
}

export interface ScrapeRequest {
  /** Mubawab search URL to scrape */
  url: string;
  /** Maximum number of leads to extract */
  maxLeads: number;
  /** Optional Groq API key to auto-generate messages */
  groqApiKey?: string;
}

export interface ScrapeResponse {
  success: boolean;
  leadsFound: number;
  leads: Lead[];
  errors?: string[];
}

export type GenerateRequestLanguage = typeof GenerateRequestLanguage[keyof typeof GenerateRequestLanguage];


export const GenerateRequestLanguage = {
  fr: 'fr',
  ar: 'ar',
} as const;

export interface GenerateRequest {
  leadId?: string;
  lead?: Lead;
  /** Custom prompt template */
  prompt?: string;
  groqApiKey: string;
  language?: GenerateRequestLanguage;
}

export interface GenerateResponse {
  message: string;
  confidenceScore: number;
  isAgency: boolean;
  suggestedSlots?: string[];
}

export interface SendRequest {
  leadId?: string;
  phone: string;
  message: string;
  mock?: boolean;
}

export interface SendResponse {
  success: boolean;
  messageId?: string;
  mock?: boolean;
  sentAt: string;
}

export interface ScheduleRequest {
  leadId: string;
  phone?: string;
  date: string;
  time: string;
  notes?: string;
}

export interface Schedule {
  id: string;
  leadId: string;
  phone?: string;
  date: string;
  time: string;
  notes?: string;
  createdAt: string;
}

export type LogEntryLevel = typeof LogEntryLevel[keyof typeof LogEntryLevel];


export const LogEntryLevel = {
  info: 'info',
  warn: 'warn',
  error: 'error',
  success: 'success',
} as const;

export interface LogEntry {
  id: string;
  level: LogEntryLevel;
  message: string;
  details?: string;
  createdAt: string;
}

export interface LogsResponse {
  logs: LogEntry[];
}

export type ConfigLanguage = typeof ConfigLanguage[keyof typeof ConfigLanguage];


export const ConfigLanguage = {
  fr: 'fr',
  ar: 'ar',
} as const;

export interface Config {
  backendUrl?: string;
  groqApiKey?: string;
  customPrompt?: string;
  maxLeads: number;
  delayMin: number;
  delayMax: number;
  language: ConfigLanguage;
  onboardingDone: boolean;
}

export type WebhookPayloadEntryItem = { [key: string]: unknown };

export interface WebhookPayload {
  object?: string;
  entry?: WebhookPayloadEntryItem[];
  [key: string]: unknown;
 }

export type UpdateConfigRequestLanguage = typeof UpdateConfigRequestLanguage[keyof typeof UpdateConfigRequestLanguage];


export const UpdateConfigRequestLanguage = {
  fr: 'fr',
  ar: 'ar',
} as const;

export interface UpdateConfigRequest {
  backendUrl?: string;
  groqApiKey?: string;
  customPrompt?: string;
  maxLeads?: number;
  delayMin?: number;
  delayMax?: number;
  language?: UpdateConfigRequestLanguage;
  onboardingDone?: boolean;
}

export type GetLeadsParams = {
status?: GetLeadsStatus;
city?: string;
limit?: number;
offset?: number;
};

export type GetLeadsStatus = typeof GetLeadsStatus[keyof typeof GetLeadsStatus];


export const GetLeadsStatus = {
  new: 'new',
  contacted: 'contacted',
  scheduled: 'scheduled',
  rejected: 'rejected',
} as const;

export type GetLogsParams = {
limit?: number;
};

